### ISSUE TITLE
Exception when pulling log data from an active well

### ISSUE THREAD

**Issue by llliuwg** [hashmapinc/witsml-client#9]
Well Name: RW 29N-29HZ
Well Legal: RW 29N-29HZ
Well Id : us_1500237601
Well Status: drilling
Found 1 WellBore
Wellbore Name: RW 29N-29HZ WB #1
Wellbore Id: us_1500237601_wb1
Found 7 Logs
Log Name: Log #1
Log Id: us_1500237601_wb1_log_1
java.lang.NullPointerException
        at java.util.stream.ReferencePipeline$6$1.accept(ReferencePipeline.java:244)
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.DoublePipeline.collect(DoublePipeline.java:476)
        at java.util.stream.DoublePipeline.summaryStatistics(DoublePipeline.java:454)
        at com.hashmapinc.tempus.witsml.api.LogRequestTracker.getMinOfMaxDepth(LogRequestTracker.java:141)
        at com.hashmapinc.tempus.witsml.api.LogRequestTracker.ExecuteRequest(LogRequestTracker.java:83)
        at com.hashmapinc.tempus.witsml.example.MyWitsmlClient.PrintLogRequest(MyWitsmlClient.java:168)
        at com.hashmapinc.tempus.witsml.example.MyWitsmlClient.lambda$PrintLogs$2(MyWitsmlClient.java:139)
        at java.util.ArrayList.forEach(ArrayList.java:1249)
        at com.hashmapinc.tempus.witsml.example.MyWitsmlClient.PrintLogs(MyWitsmlClient.java:136)
        at com.hashmapinc.tempus.witsml.example.MyWitsmlClient.lambda$PrintWellbores$1(MyWitsmlClient.java:95)
        at java.util.ArrayList.forEach(ArrayList.java:1249)
        at com.hashmapinc.tempus.witsml.example.MyWitsmlClient.PrintWellbores(MyWitsmlClient.java:90)
        at com.hashmapinc.tempus.witsml.example.MyWitsmlClient.lambda$main$0(MyWitsmlClient.java:80)
        at java.util.ArrayList.forEach(ArrayList.java:1249)
        at com.hashmapinc.tempus.witsml.example.MyWitsmlClient.main(MyWitsmlClient.java:74)

**Comment by cherrera2001** [comment]
We were able to verify this issue, there is currently a fix in TSA-204 branch that will be merged sometime today. Thanks for the report!

**Comment by llliuwg** [comment]
I have tested latest code. This issue is now fixed.
